"""Analysis Storage Service.

Persists executive analyses and consensus results to PostgreSQL
after they are generated by the existing pipeline.
"""

import logging
from typing import Any, Optional

from .database import get_session, is_database_ready
from .models import Meeting, ExecutiveAnalysis, ConsensusRecord

logger = logging.getLogger(__name__)


class StorageService:
    """Persists board meeting data to PostgreSQL."""

    async def store_meeting(
        self,
        meeting_id: str,
        proposal: str,
        business_category: str,
        title: Optional[str] = None,
        optional_context: Optional[str] = None,
    ) -> bool:
        if not is_database_ready():
            logger.debug("StorageService: DB not ready, skipping meeting storage")
            return False

        try:
            async with get_session() as session:
                meeting = Meeting(
                    meeting_id=meeting_id,
                    title=title or proposal[:200],
                    proposal=proposal,
                    business_category=business_category,
                    optional_context=optional_context,
                )
                session.add(meeting)
                await session.commit()
                logger.info(f"StorageService: Meeting {meeting_id[:8]} stored")
                return True

        except Exception as e:
            logger.error(f"StorageService: Meeting storage failed: {e}")
            return False

    async def store_analysis(
        self,
        meeting_id: str,
        executive_role: str,
        response: dict[str, Any],
    ) -> bool:
        if not is_database_ready():
            return False

        try:
            raw_pos = str(response.get("position", "neutral"))
            recommendation = raw_pos.split(".")[-1].lower() if "." in raw_pos else raw_pos.lower()

            analysis = ExecutiveAnalysis(
                meeting_id=meeting_id,
                executive_role=executive_role,
                recommendation=recommendation,
                confidence=float(response.get("confidence", 0)),
                rationale=response.get("rationale"),
                risks=response.get("risks"),
                supporting_conditions=response.get("conditions"),
                recommended_actions=(
                    response.get("recommended_actions")
                    or response.get("metrics_to_track")
                    or response.get("implementation_phases")
                    or response.get("change_management_needs")
                    or response.get("required_safeguards")
                ),
            )

            async with get_session() as session:
                session.add(analysis)
                await session.commit()
                return True

        except Exception as e:
            logger.error(f"StorageService: Analysis storage failed for {executive_role}: {e}")
            return False

    async def store_consensus(
        self,
        meeting_id: str,
        consensus: dict[str, Any],
    ) -> bool:
        if not is_database_ready():
            return False

        try:
            record = ConsensusRecord(
                meeting_id=meeting_id,
                decision=consensus.get("decision", "unknown"),
                confidence=float(consensus.get("confidence", 0)),
                summary=consensus.get("executive_summary"),
                votes={
                    "support": consensus.get("support_count", 0),
                    "conditional": consensus.get("conditional_count", 0),
                    "neutral": consensus.get("neutral_count", 0),
                    "oppose": consensus.get("oppose_count", 0),
                },
                participating_agents=consensus.get("participating_agents"),
                conflict_detected=consensus.get("conflict_detected", False),
            )

            async with get_session() as session:
                session.add(record)
                await session.commit()
                logger.info(f"StorageService: Consensus for {meeting_id[:8]} stored")
                return True

        except Exception as e:
            logger.error(f"StorageService: Consensus storage failed: {e}")
            return False

    async def store_report(
        self,
        meeting_id: str,
        report_json: dict[str, Any],
        report_pdf_base64: str,
    ) -> bool:
        """Store the generated report (JSON + PDF) for a meeting."""
        if not is_database_ready():
            return False

        try:
            from sqlalchemy import update
            async with get_session() as session:
                stmt = (
                    update(Meeting)
                    .where(Meeting.meeting_id == meeting_id)
                    .values(report_json=report_json, report_pdf=report_pdf_base64)
                )
                await session.execute(stmt)
                await session.commit()
                logger.info(f"StorageService: Report for {meeting_id[:8]} stored")
                return True

        except Exception as e:
            logger.error(f"StorageService: Report storage failed: {e}")
            return False
