"""Analysis Storage Service.

Persists executive analyses and consensus results to PostgreSQL
after they are generated by the existing pipeline.

This service is called AFTER the existing orchestration completes.
It does not modify or interfere with the current workflow.
"""

import logging
from typing import Any, Optional

from .database import get_session, is_database_ready
from .models import Meeting, ExecutiveAnalysis, ConsensusRecord

logger = logging.getLogger(__name__)


class StorageService:
    """Persists board meeting data to PostgreSQL.

    Called after orchestration and consensus complete.
    Fails gracefully if database is unavailable.
    """

    async def store_meeting(
        self,
        meeting_id: str,
        proposal: str,
        business_category: str,
        title: Optional[str] = None,
        optional_context: Optional[str] = None,
    ) -> bool:
        """Store a new meeting record.

        Returns True if stored, False if database unavailable.
        """
        if not is_database_ready():
            return False

        session = get_session()
        if not session:
            return False

        try:
            async with session:
                meeting = Meeting(
                    meeting_id=meeting_id,
                    title=title or proposal[:200],
                    proposal=proposal,
                    business_category=business_category,
                    optional_context=optional_context,
                )
                session.add(meeting)
                await session.commit()
                return True

        except Exception as e:
            logger.error(f"Meeting storage failed: {e}")
            return False

    async def store_analysis(
        self,
        meeting_id: str,
        executive_role: str,
        response: dict[str, Any],
    ) -> bool:
        """Store a single executive agent's analysis.

        Extracts fields from the agent response dict and persists them.
        """
        if not is_database_ready():
            return False

        session = get_session()
        if not session:
            return False

        try:
            # Extract position (handle enum-style values)
            raw_pos = str(response.get("position", "neutral"))
            recommendation = raw_pos.split(".")[-1].lower() if "." in raw_pos else raw_pos.lower()

            analysis = ExecutiveAnalysis(
                meeting_id=meeting_id,
                executive_role=executive_role,
                recommendation=recommendation,
                confidence=float(response.get("confidence", 0)),
                rationale=response.get("rationale"),
                risks=response.get("risks"),
                supporting_conditions=response.get("conditions"),
                recommended_actions=(
                    response.get("recommended_actions")
                    or response.get("metrics_to_track")
                    or response.get("implementation_phases")
                    or response.get("change_management_needs")
                    or response.get("required_safeguards")
                ),
                execution_time_ms=None,
            )

            async with session:
                session.add(analysis)
                await session.commit()
                return True

        except Exception as e:
            logger.error(f"Analysis storage failed for {executive_role}: {e}")
            return False

    async def store_consensus(
        self,
        meeting_id: str,
        consensus: dict[str, Any],
    ) -> bool:
        """Store the final consensus decision.

        Args:
            meeting_id: The meeting session ID.
            consensus: The consensus result dict from ConsensusEngine.
        """
        if not is_database_ready():
            return False

        session = get_session()
        if not session:
            return False

        try:
            record = ConsensusRecord(
                meeting_id=meeting_id,
                decision=consensus.get("decision", "unknown"),
                confidence=float(consensus.get("confidence", 0)),
                summary=consensus.get("executive_summary"),
                votes={
                    "support": consensus.get("support_count", 0),
                    "conditional": consensus.get("conditional_count", 0),
                    "neutral": consensus.get("neutral_count", 0),
                    "oppose": consensus.get("oppose_count", 0),
                },
                participating_agents=consensus.get("participating_agents"),
                conflict_detected=consensus.get("conflict_detected", False),
            )

            async with session:
                session.add(record)
                await session.commit()
                return True

        except Exception as e:
            logger.error(f"Consensus storage failed: {e}")
            return False
